---

- name: 'Criando diretorio do DockerFile'
  file:
    path: /tmp/Docker
    state: directory
    mode: 0755

- name: 'Usando Usuario root'
  shell: sudo su

#- name: 'Git Clone'
#  shell: sudo git clone https://github.com/daniel1541/trabalho.git

- git:
    repo: https://github.com/daniel1541/trabalho.git
    dest: /tmp/Docker
    clone: yes
    update: no

- name: 'Rodando Docker Compose'
  shell: cd /tmp/Docker/docker && docker-compose up -d
