---

- name: 'Criando diretorio do DockerFile'
  file:
    path: /tmp/Docker
    state: directory
    mode: 0755

- name: 'Usando Usuario root'
  shell: sudo su

- name: 'entrando no diretorio do Docker'
  shell: cd /tmp/Docker

- name: 'Iniciando o Git'
  shell: sudo git init

- name: 'Git Clone'
  shell: sudo git clone https://github.com/daniel1541/trabalho.git

- name: 'Rodando Docker Compose'
  shell: cd /tmp/Docker/trabalho/docker && docker-compose up -d
